name: task2
description: A Flutter app that shows how to use map and geojson.
version: 1.0.0+1
publish_to: none  

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.3
  geojson: ^1.0.0
  #flutter_map: ^0.13.1
  flutter_map_marker_cluster: ^0.4.0 
  flutter_map: ^0.14.0

dev_dependencies:
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/geojson_file_1.geojson
